### ISSUE TITLE
how to do with this repo (i'm noob)

### ISSUE THREAD

**Issue by cjrayance** [scotow/zippyst#4]
I think this is a stupid question and shouldn't be asked but Can it work on windows 10? If so, how to do it?

**Comment by scotow** [comment]
I don't have any Windows computer / server to test, but it should work just fine if you have the Rust toolchain installed on your PC and then running `cargo run YOUR_LINK` in the powershell while being in the same folder as the sources of this project.

**Comment by cjrayance** [comment]
Does Visual Studio need to be installed as well?

**Comment by scotow** [comment]
Not really, you can build / run the project without VS Code. All your questions are more related to rust itself than this project directly.
You can learn more on how to install the Rust toolchain here: https://forge.rust-lang.org/infra/other-installation-methods.html.
