### ISSUE TITLE
About file expired

### ISSUE THREAD

**Issue by quivenda** [scotow/zippyst#7]
Hi, thanks for the tools.

With the command `cargo run 'https://www3.zippyshare.com/v/CDCi2wVT/file.html'` or `xargs -a links.txt zippyst` is file expired reset to 30 days or not? or this tools only get direct links?

Before I'm using zippyst, I'm using this tool's https://github.com/Cartmanishere/zippyshare-scraper, but for some reason it stopped working.

**Comment by scotow** [comment]
That would depend on how zippyshare reset expiration: on metadata / info page fetch or on file download. So, if it's on file download, it will not reset expiration if you don't download the file.

Yeah, they try to obfuscate their key algorithm from time to time.

**Comment by quivenda** [comment]
I'm just using `curl -H "range: bytes=1"` to download the files from direct link that generated by zippyst, so it reset the expiration date to 30 days again.

Thanks for the tools, I hope it always up-to-date since zippyshare tries to obfuscate their key algorithm from time to time like You said.

Once again, thanks.
